### ISSUE TITLE
Coding Style: Author, License, meta information in files

### ISSUE THREAD

**Issue by dschier-wtd** [while-true-do/doc-library#14]
As a developer, I need some guidelines how while-true-do.io can be represented in script headers, meta files, readmes, etc. At least the following information should be addressed:

- author
- description
- company
- license
- humans.txt

**Comment by daniel-schier** [comment]
Bash could look like this:

```
#!/usr/bin/env bash
#
# name          : <name>
# author         : while-true-do.io
# description  : This script ...
# company     : while-true-do.io
# license        : BSD-3-Clause
# =============================================================================
```

ansible/meta/main.yml could look like

```
galaxy_info:
  role_name: <name>
  author: while-true-do.io
  description: This role ...
  company: while-true-do.io
  license: BSD-3-Clause
```

As you can see, some information are similar and we need to align the inormation there.
